version: '3.8'

services:
#  frontend:
##    container_name: frontend
#    build:
#      context: .
#      dockerfile: frontend.Dockerfile
#    ports:
#      - "${FRONTEND_PORT}:3000"
##    environment:
##      - VITE_API_URL=${API_URL}
#    depends_on:
#      - backend
#    networks:
#      - app-network

  backend:
#    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{HOST}:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "npx prisma migrate deploy && npm run start"

  db:
#    container_name: postgres
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge